"use client";
import "./pnr.css";

import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Clock3, Loader2, ShieldCheck, TrainFront, XCircle } from "lucide-react";

interface Passenger { number: number; bookingStatus: string; currentStatus: string; coach?: string; berth?: string; }
interface PnrResult { pnr: string; trainNumber: string; trainName: string; journeyDate: string; from: string; to: string; boardingPoint?: string; class?: string; passengers: Passenger[]; fare?: string | number; chartStatus?: string; trainStatus?: string; demo?: boolean; }

export default function PnrPage() {
  const [pnr, setPnr] = useState(""); const [result, setResult] = useState<PnrResult | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [recent, setRecent] = useState<string[]>([]);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem("express_recent_pnrs") || "[]"); if (Array.isArray(saved)) setRecent(saved.slice(0, 5)); } catch {} }, []);
  const checkPnr = async (event?: FormEvent) => { event?.preventDefault(); if (!/^\d{10}$/.test(pnr)) { setError("Please enter a valid 10-digit PNR number."); return; } setLoading(true); setError(""); setResult(null); try { const response = await fetch(`/api/pnr?pnr=${pnr}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data?.error || "Unable to fetch PNR status."); setResult(data); const next = [pnr, ...recent.filter((item) => item !== pnr)].slice(0, 5); setRecent(next); localStorage.setItem("express_recent_pnrs", JSON.stringify(next)); } catch (err) { setError(err instanceof Error ? err.message : "Unable to fetch PNR status."); } finally { setLoading(false); } };
  return <main className="pnr-page"><header className="pnr-header"><button className="pnr-back" onClick={() => window.history.back()} aria-label="Go back"><ArrowLeft size={19} /></button><div><p className="eyebrow blue">EXPRESS · TRAIN UTILITIES</p><h1>PNR Status</h1></div><div className="pnr-logo"><TrainFront size={19} /></div></header>
    <section className="pnr-card pnr-search-card"><div className="pnr-title-row"><div><p className="eyebrow">CHECK YOUR JOURNEY</p><h2>Find your PNR status</h2></div><div className="secure-badge"><ShieldCheck size={15}/> Private</div></div><p className="pnr-help">Enter your 10-digit PNR to fetch booking, coach and current status.</p><form onSubmit={checkPnr} className="pnr-form"><label htmlFor="pnr">PNR number</label><input id="pnr" inputMode="numeric" autoComplete="off" maxLength={10} value={pnr} onChange={(e) => { setPnr(e.target.value.replace(/\D/g, "").slice(0, 10)); setError(""); }} placeholder="Enter 10 digit PNR"/><div className="pnr-input-meta"><span>{pnr.length}/10 digits</span><span>PNR is kept private</span></div><button className="pnr-submit" disabled={pnr.length !== 10 || loading}>{loading ? <><Loader2 size={17} className="spin"/> Fetching status...</> : <>Check PNR <span>→</span></>}</button></form>{error && <div className="pnr-error"><XCircle size={18}/><div><strong>Couldn’t fetch PNR</strong><p>{error}</p></div></div>}</section>
    {result && <section className="pnr-result">{result.demo && <div className="demo-banner">Demo response is active. Add an authorized railway API provider in the server environment for live PNR data.</div>}<div className="pnr-train-card"><div><p className="eyebrow">TRAIN</p><h2>{result.trainNumber} · {result.trainName}</h2><p>{result.from} <span>→</span> {result.to}</p></div><div className="status-ok"><CheckCircle2 size={16}/> {result.trainStatus || "Status available"}</div></div><div className="pnr-grid"><Info label="Journey date" value={result.journeyDate}/><Info label="Boarding point" value={result.boardingPoint || result.from}/><Info label="Class" value={result.class || "—"}/><Info label="Chart status" value={result.chartStatus || "—"}/></div><div className="pnr-card passenger-card"><div className="section-mini"><div><p className="eyebrow">PASSENGERS</p><h3>Booking & current status</h3></div><span>{result.passengers.length} passenger{result.passengers.length > 1 ? "s" : ""}</span></div><div className="passenger-list">{result.passengers.map((passenger) => <div className="passenger-row" key={passenger.number}><div className="passenger-number">{passenger.number}</div><div><strong>Passenger {passenger.number}</strong><small>Booking: {passenger.bookingStatus}</small></div><div className="current-status"><b>{passenger.currentStatus}</b>{passenger.coach && <small>{passenger.coach}{passenger.berth ? ` · ${passenger.berth}` : ""}</small>}</div></div>)}</div></div><div className="pnr-bottom-grid"><Info label="Total fare" value={result.fare ? `₹${result.fare}` : "—"}/><Info label="Train status" value={result.trainStatus || "—"}/></div></section>}
    {!result && !loading && recent.length > 0 && <section className="pnr-recent"><div className="section-mini"><div><p className="eyebrow">YOUR SEARCHES</p><h3>Recent PNRs</h3></div><Clock3 size={17}/></div><div className="recent-list">{recent.map((item) => <button key={item} onClick={() => {setPnr(item);setError("")}}><span>{item}</span><span>Use →</span></button>)}</div></section>}
    {!result && recent.length === 0 && <section className="pnr-info"><div className="info-icon"><ShieldCheck size={19}/></div><div><strong>Your PNR stays private</strong><p>EXPRESS never displays your exact PNR, coach or berth to other people in the social discovery experience.</p></div></section>}
  </main>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="pnr-info-cell"><span>{label}</span><strong>{value}</strong></div>; }
